### ISSUE TITLE
No submit button on panel

### ISSUE THREAD

**Issue by jhameier** [caiosba/slack-draw#1]
Was just checking out your plugin for slack on google chrome. Plugin installs fine from both app store and crx file but when pulling up drawing panel in slack there is no submit button. I can draw on the space without issue but have no way to confirm the drawings.

**Comment by caiosba** [comment]
Thanks for reporting, I can confirm that. Will work on a fix.

**Comment by caiosba** [comment]
Fixed!

**Comment by jhameier** [comment]
Confirmed. Thanks!

On Sun, Apr 24, 2016 at 11:46 PM, Caio Almeida notifications@github.com
wrote:

> Fixed!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/caiosba/slack-draw/issues/1#issuecomment-214116662

## 

John Hameier
(856) 237-5562 cell
